-- Chess Coach schema. Designed for a single PostgreSQL 16 instance that hosts
-- the opening tree, the RAG corpus (pgvector + tsvector), user data, game
-- history, puzzles, FSRS flashcards, maia-individual practice sessions, and
-- the chat history for RAG conversations.

CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS ltree;
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- =============================================================
-- Opening tree
-- =============================================================
CREATE TABLE IF NOT EXISTS opening_nodes (
    id              BIGSERIAL PRIMARY KEY,
    parent_id       BIGINT REFERENCES opening_nodes(id),
    eco_code        VARCHAR(5),
    opening_name    TEXT,
    move_uci        VARCHAR(5),
    move_san        VARCHAR(10),
    move_sequence   TEXT NOT NULL,
    fen             TEXT NOT NULL,
    fen_canonical   TEXT GENERATED ALWAYS AS (
                        array_to_string((string_to_array(fen, ' '))[1:4], ' ')
                    ) STORED,
    depth           SMALLINT NOT NULL DEFAULT 0,
    path            ltree,

    -- Lichess explorer aggregates
    white_wins      INTEGER DEFAULT 0,
    draws           INTEGER DEFAULT 0,
    black_wins      INTEGER DEFAULT 0,
    avg_rating      SMALLINT,
    total_games     INTEGER GENERATED ALWAYS AS (
                        COALESCE(white_wins,0) + COALESCE(draws,0) + COALESCE(black_wins,0)
                    ) STORED,

    -- Coaching content generated by the local LLM
    description     TEXT,
    themes          TEXT[],
    typical_plans   JSONB,
    key_squares     TEXT[],

    created_at      TIMESTAMPTZ DEFAULT NOW(),
    updated_at      TIMESTAMPTZ DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_opening_fen_canonical ON opening_nodes (fen_canonical);
CREATE INDEX IF NOT EXISTS idx_opening_parent ON opening_nodes (parent_id);
CREATE INDEX IF NOT EXISTS idx_opening_eco    ON opening_nodes (eco_code);
CREATE INDEX IF NOT EXISTS idx_opening_path   ON opening_nodes USING gist (path);
CREATE INDEX IF NOT EXISTS idx_opening_name_trgm ON opening_nodes USING gin (opening_name gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_opening_depth  ON opening_nodes (depth);
CREATE INDEX IF NOT EXISTS idx_opening_themes ON opening_nodes USING gin (themes);

-- =============================================================
-- Wikipedia / Wikidata source content for opening descriptions.
--
-- Populated from the Wikidata SPARQL endpoint + the MediaWiki Extracts API.
-- Every row is a Wikipedia article about a chess opening, keyed by the
-- Wikidata Q-id. ``eco_code`` and ``title`` are matched against opening_nodes
-- to decide which tree node a row should hydrate.
-- =============================================================
CREATE TABLE IF NOT EXISTS wiki_openings (
    id              BIGSERIAL PRIMARY KEY,
    wikidata_qid    VARCHAR(20) UNIQUE NOT NULL,
    title           TEXT NOT NULL,
    eco_code        VARCHAR(5),
    aliases         TEXT[],
    wikipedia_url   TEXT,
    extract         TEXT NOT NULL,
    revision_id     BIGINT,
    fetched_at      TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_wiki_eco   ON wiki_openings (eco_code);
CREATE INDEX IF NOT EXISTS idx_wiki_title_trgm ON wiki_openings USING gin (title gin_trgm_ops);

-- =============================================================
-- RAG corpus
-- =============================================================
CREATE TABLE IF NOT EXISTS rag_documents (
    id               BIGSERIAL PRIMARY KEY,
    opening_node_id  BIGINT REFERENCES opening_nodes(id),
    chunk_level      VARCHAR(20) NOT NULL
                     CHECK (chunk_level IN ('family','variation','position','theme')),
    title            TEXT NOT NULL,
    content          TEXT NOT NULL,
    content_tsvector TSVECTOR GENERATED ALWAYS AS (
                         to_tsvector('english', content)
                     ) STORED,
    embedding        vector(1024),
    metadata         JSONB NOT NULL DEFAULT '{}',
    source_type      VARCHAR(30) DEFAULT 'llm_generated',
    source_model     VARCHAR(80),
    verified         BOOLEAN DEFAULT FALSE,
    created_at       TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_rag_embedding_hnsw
    ON rag_documents USING hnsw (embedding vector_cosine_ops)
    WITH (m = 16, ef_construction = 128);
CREATE INDEX IF NOT EXISTS idx_rag_content_fts  ON rag_documents USING gin (content_tsvector);
CREATE INDEX IF NOT EXISTS idx_rag_chunk_level  ON rag_documents (chunk_level);
CREATE INDEX IF NOT EXISTS idx_rag_opening_node ON rag_documents (opening_node_id);
CREATE INDEX IF NOT EXISTS idx_rag_metadata     ON rag_documents USING gin (metadata jsonb_path_ops);

-- =============================================================
-- Users
-- =============================================================
CREATE TABLE IF NOT EXISTS users (
    id              BIGSERIAL PRIMARY KEY,
    username        VARCHAR(50) UNIQUE NOT NULL,
    email           VARCHAR(255) UNIQUE,
    chess_com_user  VARCHAR(50),
    lichess_user    VARCHAR(50),
    current_rating  JSONB DEFAULT '{}',
    puzzle_rating   REAL DEFAULT 1500.0,
    puzzle_rd       REAL DEFAULT 350.0,
    puzzle_vol      REAL DEFAULT 0.06,
    preferences     JSONB DEFAULT '{}',
    created_at      TIMESTAMPTZ DEFAULT NOW(),
    updated_at      TIMESTAMPTZ DEFAULT NOW()
);

-- =============================================================
-- Imported game history
-- =============================================================
CREATE TABLE IF NOT EXISTS user_games (
    id                BIGSERIAL PRIMARY KEY,
    user_id           BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    source            VARCHAR(10) NOT NULL CHECK (source IN ('chess_com','lichess')),
    external_id       VARCHAR(64) NOT NULL,
    pgn               TEXT NOT NULL,
    fen_final         TEXT,
    eco_code          VARCHAR(5),
    opening_name      TEXT,
    opening_node_id   BIGINT REFERENCES opening_nodes(id),

    user_color        VARCHAR(5) NOT NULL CHECK (user_color IN ('white','black')),
    user_rating       SMALLINT,
    opponent_name     VARCHAR(50),
    opponent_rating   SMALLINT,
    result            VARCHAR(20) NOT NULL,
    result_detail     VARCHAR(30),
    accuracy          REAL,

    time_control      VARCHAR(20),
    time_class        VARCHAR(20),
    played_at         TIMESTAMPTZ NOT NULL,
    move_count        SMALLINT,

    opening_accuracy  REAL,
    first_mistake_ply SMALLINT,
    deviation_ply     SMALLINT,

    created_at        TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE (user_id, source, external_id)
);

CREATE INDEX IF NOT EXISTS idx_games_user     ON user_games (user_id);
CREATE INDEX IF NOT EXISTS idx_games_opening  ON user_games (opening_node_id);
CREATE INDEX IF NOT EXISTS idx_games_eco      ON user_games (eco_code);
CREATE INDEX IF NOT EXISTS idx_games_played   ON user_games (played_at DESC);
CREATE INDEX IF NOT EXISTS idx_games_result   ON user_games (user_id, result);
CREATE INDEX IF NOT EXISTS idx_games_opponent ON user_games (opponent_name);

-- Games used only as training material for a maia-individual model.
-- Pulled from /pub/player/{opponent}/games/* without being attached to a user_id.
CREATE TABLE IF NOT EXISTS opponent_games (
    id            BIGSERIAL PRIMARY KEY,
    opponent      VARCHAR(50) NOT NULL,
    source        VARCHAR(10) NOT NULL CHECK (source IN ('chess_com','lichess')),
    external_id   VARCHAR(64) NOT NULL,
    pgn           TEXT NOT NULL,
    opponent_color VARCHAR(5) NOT NULL CHECK (opponent_color IN ('white','black')),
    opponent_rating SMALLINT,
    time_class    VARCHAR(20),
    played_at     TIMESTAMPTZ,
    created_at    TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE (opponent, source, external_id)
);
CREATE INDEX IF NOT EXISTS idx_oppgames_opp ON opponent_games (opponent);

-- =============================================================
-- Weakness tracking
-- =============================================================
CREATE TABLE IF NOT EXISTS user_weaknesses (
    id                BIGSERIAL PRIMARY KEY,
    user_id           BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    opening_node_id   BIGINT NOT NULL REFERENCES opening_nodes(id),
    color             VARCHAR(5) NOT NULL,

    games_played      INTEGER DEFAULT 0,
    wins              INTEGER DEFAULT 0,
    draws             INTEGER DEFAULT 0,
    losses            INTEGER DEFAULT 0,
    win_rate          REAL GENERATED ALWAYS AS (
                          CASE WHEN games_played > 0
                               THEN wins::real / games_played
                               ELSE 0 END
                      ) STORED,
    avg_accuracy      REAL,
    avg_deviation_ply REAL,

    weakness_score    REAL DEFAULT 0.0,
    weakness_type     VARCHAR(30),
    last_computed     TIMESTAMPTZ DEFAULT NOW(),

    UNIQUE (user_id, opening_node_id, color)
);
CREATE INDEX IF NOT EXISTS idx_weakness_user    ON user_weaknesses (user_id, weakness_score DESC);
CREATE INDEX IF NOT EXISTS idx_weakness_opening ON user_weaknesses (opening_node_id);

-- =============================================================
-- Flashcards (FSRS v6)
-- =============================================================
CREATE TABLE IF NOT EXISTS flashcards (
    id              BIGSERIAL PRIMARY KEY,
    user_id         BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    opening_node_id BIGINT REFERENCES opening_nodes(id),
    fen             TEXT,
    card_type       VARCHAR(20) NOT NULL
                    CHECK (card_type IN ('move_quiz','concept','plan','trap','transposition')),

    front_text      TEXT NOT NULL,
    back_text       TEXT NOT NULL,
    front_image_url TEXT,
    hint            TEXT,
    tags            TEXT[],

    state           SMALLINT NOT NULL DEFAULT 0,
    step            SMALLINT DEFAULT 0,
    stability       REAL DEFAULT 0.0,
    difficulty      REAL DEFAULT 0.0,
    due             TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_review     TIMESTAMPTZ,
    scheduled_days  INTEGER DEFAULT 0,
    reps            INTEGER DEFAULT 0,
    lapses          INTEGER DEFAULT 0,

    generated_by    VARCHAR(50) DEFAULT 'llm',
    source_model    VARCHAR(80),
    verified        BOOLEAN DEFAULT FALSE,

    created_at      TIMESTAMPTZ DEFAULT NOW(),
    updated_at      TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_flashcard_due       ON flashcards (user_id, due) WHERE state != 0;
CREATE INDEX IF NOT EXISTS idx_flashcard_user_type ON flashcards (user_id, card_type);
CREATE INDEX IF NOT EXISTS idx_flashcard_opening   ON flashcards (opening_node_id);
CREATE INDEX IF NOT EXISTS idx_flashcard_tags      ON flashcards USING gin (tags);

CREATE TABLE IF NOT EXISTS flashcard_reviews (
    id                 BIGSERIAL PRIMARY KEY,
    flashcard_id       BIGINT NOT NULL REFERENCES flashcards(id) ON DELETE CASCADE,
    user_id            BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    rating             SMALLINT NOT NULL CHECK (rating BETWEEN 1 AND 4),
    state_before       SMALLINT NOT NULL,
    stability_before   REAL,
    difficulty_before  REAL,
    elapsed_days       REAL,
    review_duration_ms INTEGER,
    reviewed_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_review_flashcard ON flashcard_reviews (flashcard_id, reviewed_at DESC);
CREATE INDEX IF NOT EXISTS idx_review_user      ON flashcard_reviews (user_id, reviewed_at DESC);

-- =============================================================
-- Puzzles (Glicko-2)
-- =============================================================
CREATE TABLE IF NOT EXISTS puzzles (
    id               BIGSERIAL PRIMARY KEY,
    source_game_id   BIGINT REFERENCES user_games(id) ON DELETE SET NULL,
    opening_node_id  BIGINT REFERENCES opening_nodes(id),
    fen              TEXT NOT NULL,
    fen_canonical    TEXT,
    setup_move_uci   VARCHAR(5),
    solution_uci     TEXT[] NOT NULL,
    solution_san     TEXT[],
    played_move_uci  VARCHAR(5),

    themes           TEXT[],
    opening_phase    BOOLEAN DEFAULT TRUE,
    piece_count      SMALLINT,
    solution_depth   SMALLINT,

    rating           REAL DEFAULT 1500.0,
    rating_rd        REAL DEFAULT 350.0,
    rating_vol       REAL DEFAULT 0.06,
    attempts         INTEGER DEFAULT 0,
    solves           INTEGER DEFAULT 0,

    eval_before      REAL,
    eval_after       REAL,
    eval_swing       REAL,

    hint_text        TEXT,
    explanation      TEXT,
    explanation_model VARCHAR(80),

    source           VARCHAR(20) DEFAULT 'generated'
                     CHECK (source IN ('generated','lichess','custom')),
    created_at       TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_puzzle_rating  ON puzzles (rating);
CREATE INDEX IF NOT EXISTS idx_puzzle_opening ON puzzles (opening_node_id);
CREATE INDEX IF NOT EXISTS idx_puzzle_themes  ON puzzles USING gin (themes);
CREATE INDEX IF NOT EXISTS idx_puzzle_fen     ON puzzles (fen_canonical);

CREATE TABLE IF NOT EXISTS puzzle_attempts (
    id                   BIGSERIAL PRIMARY KEY,
    puzzle_id            BIGINT NOT NULL REFERENCES puzzles(id) ON DELETE CASCADE,
    user_id              BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    solved               BOOLEAN NOT NULL,
    moves_played         TEXT[],
    time_spent_ms        INTEGER,
    hint_used            BOOLEAN DEFAULT FALSE,
    user_rating_before   REAL,
    user_rating_after    REAL,
    puzzle_rating_before REAL,
    puzzle_rating_after  REAL,
    attempted_at         TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_attempt_user   ON puzzle_attempts (user_id, attempted_at DESC);
CREATE INDEX IF NOT EXISTS idx_attempt_puzzle ON puzzle_attempts (puzzle_id);

-- =============================================================
-- Maia practice sessions
-- =============================================================
CREATE TABLE IF NOT EXISTS maia_models (
    id                BIGSERIAL PRIMARY KEY,
    opponent          VARCHAR(50) NOT NULL,                -- chess.com username
    base_weights      TEXT NOT NULL,                       -- path to the maia-1 base weights used
    weights_path      TEXT NOT NULL,                       -- path to the fine-tuned .pb.gz
    games_trained_on  INTEGER NOT NULL,
    trained_at        TIMESTAMPTZ DEFAULT NOW(),
    notes             TEXT,
    UNIQUE (opponent, weights_path)
);

CREATE TABLE IF NOT EXISTS practice_sessions (
    id               BIGSERIAL PRIMARY KEY,
    user_id          BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    session_type     VARCHAR(20) NOT NULL
                     CHECK (session_type IN ('opening_drill','full_game','position')),
    opening_node_id  BIGINT REFERENCES opening_nodes(id),
    maia_model_id    BIGINT REFERENCES maia_models(id),
    opponent_profile VARCHAR(50),

    pgn              TEXT,
    fen_start        TEXT,
    fen_final        TEXT,
    result           VARCHAR(10),
    move_count       SMALLINT,
    user_color       VARCHAR(5),

    accuracy         REAL,
    critical_moments JSONB,
    debrief_text     TEXT,

    started_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ended_at         TIMESTAMPTZ,
    duration_sec     INTEGER
);
CREATE INDEX IF NOT EXISTS idx_session_user     ON practice_sessions (user_id, started_at DESC);
CREATE INDEX IF NOT EXISTS idx_session_opening  ON practice_sessions (opening_node_id);
CREATE INDEX IF NOT EXISTS idx_session_opponent ON practice_sessions (opponent_profile);

-- =============================================================
-- Study plans
-- =============================================================
CREATE TABLE IF NOT EXISTS study_plans (
    id              BIGSERIAL PRIMARY KEY,
    user_id         BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title           TEXT NOT NULL,
    description     TEXT,
    target_openings BIGINT[],
    plan_config     JSONB NOT NULL,
    status          VARCHAR(15) DEFAULT 'active',
    created_at      TIMESTAMPTZ DEFAULT NOW(),
    updated_at      TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS study_sessions (
    id              BIGSERIAL PRIMARY KEY,
    user_id         BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    study_plan_id   BIGINT REFERENCES study_plans(id) ON DELETE SET NULL,
    session_type    VARCHAR(20) NOT NULL,
    opening_node_id BIGINT REFERENCES opening_nodes(id),
    duration_sec    INTEGER,
    items_completed INTEGER DEFAULT 0,
    accuracy        REAL,
    notes           TEXT,
    started_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ended_at        TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_study_session_user ON study_sessions (user_id, started_at DESC);

-- =============================================================
-- RAG conversations
-- =============================================================
CREATE TABLE IF NOT EXISTS rag_conversations (
    id              BIGSERIAL PRIMARY KEY,
    user_id         BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title           TEXT,
    context_fen     TEXT,
    opening_node_id BIGINT REFERENCES opening_nodes(id),
    created_at      TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS rag_messages (
    id                BIGSERIAL PRIMARY KEY,
    conversation_id   BIGINT NOT NULL REFERENCES rag_conversations(id) ON DELETE CASCADE,
    role              VARCHAR(10) NOT NULL CHECK (role IN ('user','assistant','system')),
    content           TEXT NOT NULL,
    retrieved_doc_ids BIGINT[],
    model_used        VARCHAR(80),
    tokens_used       INTEGER,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_msg_conversation ON rag_messages (conversation_id, created_at);
